# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 5
create_project -in_memory -part xc7a200tfbg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/a000_real_side/logic_eth/project_1/project_1.cache/wt [current_project]
set_property parent.project_path E:/a000_real_side/logic_eth/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/a000_real_side/logic_eth/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/a000_real_side/logic_eth/coe/sine_wave.coe
read_verilog -library xil_defaultlib {
  E:/a000_real_side/logic_eth/src/UDP/ARP_Table.v
  E:/a000_real_side/logic_eth/src/UDP/ARP_rx.v
  E:/a000_real_side/logic_eth/src/UDP/ARP_tx.v
  E:/a000_real_side/logic_eth/src/cdc/AXIS_BUF_2CLK_16X16.v
  E:/a000_real_side/logic_eth/src/cdc/AXIS_BUF_2CLK_8X2048.v
  E:/a000_real_side/logic_eth/src/ddr_ctrl/AXI_Master_Drive.v
  E:/a000_real_side/logic_eth/src/clk/CLK_DIV_module.v
  E:/a000_real_side/logic_eth/src/UDP/CRC32_D8.v
  E:/a000_real_side/logic_eth/src/UDP/CRC_Data_Pro.v
  E:/a000_real_side/logic_eth/src/ddr_ctrl/DDR_Ctrl.v
  E:/a000_real_side/logic_eth/src/UDP/Data_2to1.v
  E:/a000_real_side/logic_eth/src/UDP/Ethernet_ARP.v
  E:/a000_real_side/logic_eth/src/UDP/Ethernet_ICMP.v
  E:/a000_real_side/logic_eth/src/UDP/Ethernet_IP.v
  E:/a000_real_side/logic_eth/src/UDP/Ethernet_MAC.v
  E:/a000_real_side/logic_eth/src/UDP/Ethernet_UDP.v
  E:/a000_real_side/logic_eth/src/UDP/GMII2RGMII_Drive.v
  E:/a000_real_side/logic_eth/src/UDP/ICMP_rx.v
  E:/a000_real_side/logic_eth/src/UDP/ICMP_tx.v
  E:/a000_real_side/logic_eth/src/UDP/IP_rx.v
  E:/a000_real_side/logic_eth/src/UDP/IP_tx.v
  E:/a000_real_side/logic_eth/src/sm4/Key_Extending.v
  E:/a000_real_side/logic_eth/src/LFSR/LFSR_Gen.v
  E:/a000_real_side/logic_eth/src/UDP/MAC_rx.v
  E:/a000_real_side/logic_eth/src/UDP/MAC_tx.v
  E:/a000_real_side/logic_eth/src/UDP/RGMII_RAM.v
  E:/a000_real_side/logic_eth/src/UDP/RGMII_Tri.v
  E:/a000_real_side/logic_eth/src/sm4/Round_Function.v
  E:/a000_real_side/logic_eth/src/sm4/SM4_Decrypt.v
  E:/a000_real_side/logic_eth/src/sm4/S_Box.v
  E:/a000_real_side/logic_eth/src/UDP/UDP_Stack_Module.v
  E:/a000_real_side/logic_eth/src/UDP_Type_Gether.v
  E:/a000_real_side/logic_eth/src/UDP_Type_Spilt.v
  E:/a000_real_side/logic_eth/src/UDP/UDP_rx.v
  E:/a000_real_side/logic_eth/src/UDP/UDP_tx.v
  E:/a000_real_side/logic_eth/src/Remote_update/Updata_Ctrl.v
  E:/a000_real_side/logic_eth/src/Remote_update/Updata_TOP.v
  E:/a000_real_side/logic_eth/src/Remote_update/Updata_reply.v
  E:/a000_real_side/logic_eth/src/scope/adc_drive.v
  E:/a000_real_side/logic_eth/src/aurora/aurora_8b10b_0_cdc_sync_exdes.v
  E:/a000_real_side/logic_eth/src/aurora/aurora_8b10b_0_clock_module.v
  E:/a000_real_side/logic_eth/src/aurora/aurora_8b10b_0_gt_common_wrapper.v
  E:/a000_real_side/logic_eth/src/aurora/aurora_8b10b_0_support_reset_logic.v
  E:/a000_real_side/logic_eth/src/aurora/aurora_channel.v
  E:/a000_real_side/logic_eth/src/aurora/aurora_module.v
  E:/a000_real_side/logic_eth/src/scope/comparer.v
  E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/imports/src/dds/dds_ctrl.v
  E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/imports/src/dds/dds_drive/dds_drive.v
  E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/imports/src/dds/dds_drive/dds_saw_gen.v
  E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/imports/src/dds/dds_single_channel_top.v
  E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/imports/src/dds/dds_drive/dds_squ_gen.v
  E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/imports/src/dds/dds_drive/dds_tri_gen.v
  E:/a000_real_side/logic_eth/src/uart_adaptive/decoder_8B10B.v
  E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
  E:/a000_real_side/logic_eth/src/protocol_analyze/flash_ctrl.v
  E:/a000_real_side/logic_eth/src/protocol_analyze/flash_drive.v
  E:/a000_real_side/logic_eth/src/scope/frq_measure.v
  E:/a000_real_side/logic_eth/src/protocol_analyze/iic_drive.v
  E:/a000_real_side/logic_eth/src/protocol_analyze/iic_stream_rx.v
  E:/a000_real_side/logic_eth/src/logic/logic_top.v
  E:/a000_real_side/logic_eth/src/UDP/mac_arp_ip_mux.v
  E:/a000_real_side/logic_eth/src/scope/measure_max_min.v
  E:/a000_real_side/logic_eth/src/scope/measure_top.v
  E:/a000_real_side/logic_eth/src/scope/one_channel_truth_table_detect.v
  E:/a000_real_side/logic_eth/src/rst/rst_gen_module.v
  E:/a000_real_side/logic_eth/src/logic/sample_clk_gen.v
  E:/a000_real_side/logic_eth/src/logic/sample_data_gen.v
  E:/a000_real_side/logic_eth/src/scope_UDP_Packet.v
  E:/a000_real_side/logic_eth/src/scope/scope_data_gen.v
  E:/a000_real_side/logic_eth/src/scope/scope_top.v
  E:/a000_real_side/logic_eth/src/protocol_analyze/spi_drive.v
  E:/a000_real_side/logic_eth/src/protocol_analyze/spi_stream_rx.v
  E:/a000_real_side/logic_eth/src/scope/timer_1s.v
  E:/a000_real_side/logic_eth/src/scope/timer_triger.v
  E:/a000_real_side/logic_eth/src/uart_adaptive/uart_adaptive_baud_rate.v
  E:/a000_real_side/logic_eth/src/uart_adaptive/uart_rx_dma.v
  E:/a000_real_side/logic_eth/src/protocol_analyze/uart_stream_rx.v
  E:/a000_real_side/logic_eth/src/uart_adaptive/uart_tx.v
  E:/a000_real_side/logic_eth/src/uart_adaptive/uart_tx_dma.v
  E:/a000_real_side/logic_eth/src/bus/uart_type_spilt.v
  E:/a000_real_side/logic_eth/src/top.v
}
add_files E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr0_0.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_psr_aclk2_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_psr_aclk2_0.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_48ac_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/bd_48ac_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/bd_48ac_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/bd_48ac_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/bd_48ac_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/bd_48ac_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/bd_48ac_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/bd_48ac_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/bd_48ac_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/bd_48ac_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_32/bd_48ac_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_33/bd_48ac_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

read_ip -quiet E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/rom_sin_256/rom_sin_256.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/rom_sin_256/rom_sin_256_ooc.xdc]

read_ip -quiet E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/ASYNC_FIFO_1X16/ASYNC_FIFO_1X16.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/ASYNC_FIFO_1X16/ASYNC_FIFO_1X16.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/ASYNC_FIFO_1X16/ASYNC_FIFO_1X16_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/ASYNC_FIFO_1X16/ASYNC_FIFO_1X16_ooc.xdc]

read_ip -quiet E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_8X512/FIFO_8X512.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_8X512/FIFO_8X512.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_8X512/FIFO_8X512_ooc.xdc]

read_ip -quiet E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/mmcm/mmcm.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/mmcm/mmcm_board.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/mmcm/mmcm.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/mmcm/mmcm_ooc.xdc]

read_ip -quiet E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_16X16_2CLK/FIFO_16X16_2CLK.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_16X16_2CLK/FIFO_16X16_2CLK.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_16X16_2CLK/FIFO_16X16_2CLK_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_16X16_2CLK/FIFO_16X16_2CLK_ooc.xdc]

read_ip -quiet E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/mmcm_125/mmcm_125.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/mmcm_125/mmcm_125_board.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/mmcm_125/mmcm_125.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/mmcm_125/mmcm_125_late.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/mmcm_125/mmcm_125_ooc.xdc]

read_ip -quiet E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/FIFO_8X256/FIFO_8X256.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/FIFO_8X256/FIFO_8X256.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/FIFO_8X256/FIFO_8X256_ooc.xdc]

read_ip -quiet E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/FIFO_ASYNC_11_64/FIFO_ASYNC_11_64.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/FIFO_ASYNC_11_64/FIFO_ASYNC_11_64.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/FIFO_ASYNC_11_64/FIFO_ASYNC_11_64_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/FIFO_ASYNC_11_64/FIFO_ASYNC_11_64_ooc.xdc]

read_ip -quiet E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/FIFO_32X16/FIFO_32X16.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/FIFO_32X16/FIFO_32X16.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/FIFO_32X16/FIFO_32X16_ooc.xdc]

read_ip -quiet E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/FIFO_MAC_8X64/FIFO_MAC_8X64.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/FIFO_MAC_8X64/FIFO_MAC_8X64.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/FIFO_MAC_8X64/FIFO_MAC_8X64_ooc.xdc]

read_ip -quiet E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/RAM_8_1600/RAM_8_1600.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/RAM_8_1600/RAM_8_1600_ooc.xdc]

read_ip -quiet E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/RAM_MAC/RAM_MAC.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/RAM_MAC/RAM_MAC_ooc.xdc]

read_ip -quiet E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/RAM_IP/RAM_IP.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/RAM_IP/RAM_IP_ooc.xdc]

read_ip -quiet E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/RAM_8x1500_TrueDual/RAM_8x1500_TrueDual.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/RAM_8x1500_TrueDual/RAM_8x1500_TrueDual_ooc.xdc]

read_ip -quiet E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/FIFO_16X64/FIFO_16X64.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/FIFO_16X64/FIFO_16X64.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/FIFO_16X64/FIFO_16X64_ooc.xdc]

read_ip -quiet E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/FIFO_11X64/FIFO_11X64.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/FIFO_11X64/FIFO_11X64.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/FIFO_11X64/FIFO_11X64_ooc.xdc]

read_ip -quiet E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_8X16/FIFO_8X16.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_8X16/FIFO_8X16.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_8X16/FIFO_8X16_ooc.xdc]

read_ip -quiet E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_8X1024/FIFO_8X1024.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_8X1024/FIFO_8X1024.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_8X1024/FIFO_8X1024_ooc.xdc]

read_ip -quiet E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_8X2048/FIFO_8X2048.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_8X2048/FIFO_8X2048.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_8X2048/FIFO_8X2048_ooc.xdc]

read_ip -quiet E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_32X512/FIFO_32X512.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_32X512/FIFO_32X512.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_32X512/FIFO_32X512_ooc.xdc]

read_ip -quiet E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_32to16_512/FIFO_32to16_512.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_32to16_512/FIFO_32to16_512.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_32to16_512/FIFO_32to16_512_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_32to16_512/FIFO_32to16_512_ooc.xdc]

read_ip -quiet E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/BRAM_8X1024/BRAM_8X1024.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/BRAM_8X1024/BRAM_8X1024_ooc.xdc]

read_ip -quiet E:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_8X2048_2CLK/FIFO_8X2048_2CLK.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_8X2048_2CLK/FIFO_8X2048_2CLK.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_8X2048_2CLK/FIFO_8X2048_2CLK_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_8X2048_2CLK/FIFO_8X2048_2CLK_ooc.xdc]

read_ip -quiet e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_10X128/FIFO_10X128.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_10X128/FIFO_10X128.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_10X128/FIFO_10X128_ooc.xdc]

read_ip -quiet e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/aurora_8b10b_0/aurora_8b10b_0.xci
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/aurora_8b10b_0/aurora_8b10b_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/aurora_8b10b_0/aurora_8b10b_0.xdc]
set_property used_in_implementation false [get_files -all e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/aurora_8b10b_0/aurora_8b10b_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/a000_real_side/logic_eth/project_1/project_1.srcs/constrs_1/new/sm.xdc
set_property used_in_implementation false [get_files E:/a000_real_side/logic_eth/project_1/project_1.srcs/constrs_1/new/sm.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a200tfbg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
