set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets i_clk]

set_property IOSTANDARD LVCMOS33 [get_ports {i_rxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_rxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_rxd[0]}]
set_property PACKAGE_PIN Y19 [get_ports {i_rxd[3]}]
set_property PACKAGE_PIN AB22 [get_ports {i_rxd[2]}]
set_property PACKAGE_PIN AB21 [get_ports {i_rxd[1]}]
set_property PACKAGE_PIN Y22 [get_ports {i_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_txd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_txd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_txd[0]}]
set_property PACKAGE_PIN P20 [get_ports {o_txd[3]}]
set_property PACKAGE_PIN T20 [get_ports {o_txd[2]}]
set_property PACKAGE_PIN W21 [get_ports {o_txd[1]}]
set_property PACKAGE_PIN W22 [get_ports {o_txd[0]}]
set_property PACKAGE_PIN R4 [get_ports i_clk]
set_property IOSTANDARD LVCMOS15 [get_ports i_clk]
set_property PACKAGE_PIN Y21 [get_ports i_rx_ctl]
set_property PACKAGE_PIN W20 [get_ports o_tx_ctl]
set_property PACKAGE_PIN Y18 [get_ports i_rxc]
set_property PACKAGE_PIN W19 [get_ports o_txc]
set_property IOSTANDARD LVCMOS33 [get_ports i_rx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports i_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports o_tx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports o_txc]

set_property PACKAGE_PIN E14 [get_ports i_uart_rx]
set_property PACKAGE_PIN D17 [get_ports o_uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports o_uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports i_uart_rx]

set_property IOSTANDARD LVCMOS33 [get_ports o_dds1_clk]
set_property PACKAGE_PIN E16 [get_ports o_dds1_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds1_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds1_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds1_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds1_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds1_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds1_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds1_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds1_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds1_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds1_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds1_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds1_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds1_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds1_data[0]}]
set_property PACKAGE_PIN D16 [get_ports {o_dds1_data[13]}]
set_property PACKAGE_PIN D14 [get_ports {o_dds1_data[12]}]
set_property PACKAGE_PIN B21 [get_ports {o_dds1_data[10]}]
set_property PACKAGE_PIN B22 [get_ports {o_dds1_data[8]}]
set_property PACKAGE_PIN D20 [get_ports {o_dds1_data[6]}]
set_property PACKAGE_PIN B20 [get_ports {o_dds1_data[4]}]
set_property PACKAGE_PIN C18 [get_ports {o_dds1_data[2]}]
set_property PACKAGE_PIN B15 [get_ports {o_dds1_data[0]}]
set_property PACKAGE_PIN D15 [get_ports {o_dds1_data[11]}]
set_property PACKAGE_PIN A21 [get_ports {o_dds1_data[9]}]
set_property PACKAGE_PIN C22 [get_ports {o_dds1_data[7]}]
set_property PACKAGE_PIN C20 [get_ports {o_dds1_data[5]}]
set_property PACKAGE_PIN A20 [get_ports {o_dds1_data[3]}]
set_property PACKAGE_PIN C19 [get_ports {o_dds1_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports o_dds2_clk]
set_property PACKAGE_PIN B16 [get_ports o_dds2_clk]
set_property PACKAGE_PIN C14 [get_ports {o_dds2_data[13]}]
set_property PACKAGE_PIN C13 [get_ports {o_dds2_data[11]}]
set_property PACKAGE_PIN AB18 [get_ports {o_dds2_data[9]}]
set_property PACKAGE_PIN U18 [get_ports {o_dds2_data[7]}]
set_property PACKAGE_PIN W17 [get_ports {o_dds2_data[5]}]
set_property PACKAGE_PIN P16 [get_ports {o_dds2_data[3]}]
set_property PACKAGE_PIN R16 [get_ports {o_dds2_data[1]}]
set_property PACKAGE_PIN C15 [get_ports {o_dds2_data[12]}]
set_property PACKAGE_PIN B13 [get_ports {o_dds2_data[10]}]
set_property PACKAGE_PIN AA18 [get_ports {o_dds2_data[8]}]
set_property PACKAGE_PIN U17 [get_ports {o_dds2_data[6]}]
set_property PACKAGE_PIN V17 [get_ports {o_dds2_data[4]}]
set_property PACKAGE_PIN R17 [get_ports {o_dds2_data[2]}]
set_property PACKAGE_PIN P15 [get_ports {o_dds2_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {o_dds2_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds2_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds2_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds2_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds2_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds2_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds2_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds2_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds2_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds2_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds2_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds2_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds2_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dds2_data[0]}]



set_property IOSTANDARD LVCMOS33 [get_ports {i_adc_digit[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc_digit[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc_digit[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc_digit[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc_digit[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc_digit[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc_digit[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc_digit[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc_digit[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc_digit[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc_digit[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_adc_digit[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports o_adc_clk]
set_property PACKAGE_PIN Y14 [get_ports o_adc_clk]
set_property PACKAGE_PIN T16 [get_ports {i_adc_digit[1]}]
set_property PACKAGE_PIN V13 [get_ports {i_adc_digit[3]}]
set_property PACKAGE_PIN T14 [get_ports {i_adc_digit[5]}]
set_property PACKAGE_PIN AA9 [get_ports {i_adc_digit[7]}]
set_property PACKAGE_PIN V10 [get_ports {i_adc_digit[9]}]
set_property PACKAGE_PIN Y17 [get_ports {i_adc_digit[11]}]
set_property PACKAGE_PIN W14 [get_ports {i_adc_digit[0]}]
set_property PACKAGE_PIN U16 [get_ports {i_adc_digit[2]}]
set_property PACKAGE_PIN V14 [get_ports {i_adc_digit[4]}]
set_property PACKAGE_PIN T15 [get_ports {i_adc_digit[6]}]
set_property PACKAGE_PIN AB10 [get_ports {i_adc_digit[8]}]
set_property PACKAGE_PIN W10 [get_ports {i_adc_digit[10]}]

set_property IOSTANDARD LVCMOS33 [get_ports {i_1_rxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_1_rxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_1_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_1_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_1_txd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_1_txd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_1_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_1_txd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports i_1_rx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports i_1_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports o_1_tx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports o_1_txc]
set_property PACKAGE_PIN AA21 [get_ports {i_1_rxd[0]}]
set_property PACKAGE_PIN V20 [get_ports {i_1_rxd[1]}]
set_property PACKAGE_PIN U22 [get_ports {i_1_rxd[2]}]
set_property PACKAGE_PIN V22 [get_ports {i_1_rxd[3]}]
set_property PACKAGE_PIN T21 [get_ports {o_1_txd[0]}]
set_property PACKAGE_PIN U21 [get_ports {o_1_txd[1]}]
set_property PACKAGE_PIN P19 [get_ports {o_1_txd[2]}]
set_property PACKAGE_PIN R19 [get_ports {o_1_txd[3]}]
set_property PACKAGE_PIN AA20 [get_ports i_1_rx_ctl]
set_property PACKAGE_PIN U20 [get_ports i_1_rxc]
set_property PACKAGE_PIN V18 [get_ports o_1_txc]
set_property PACKAGE_PIN V19 [get_ports o_1_tx_ctl]



set_property IOSTANDARD LVCMOS33 [get_ports {o_spi_wp_hold[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_spi_wp_hold[0]}]
set_property PACKAGE_PIN R21 [get_ports {o_spi_wp_hold[1]}]
set_property PACKAGE_PIN P21 [get_ports {o_spi_wp_hold[0]}]
set_property PACKAGE_PIN R22 [get_ports i_spi_miso]
set_property PACKAGE_PIN P22 [get_ports o_spi_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports i_spi_miso]
set_property IOSTANDARD LVCMOS33 [get_ports o_spi_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports o_spi_cs]
set_property PACKAGE_PIN T19 [get_ports o_spi_cs]





create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list mmcm_125_u0/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {UDP_Type_Gether_u0/o_send_data[0]} {UDP_Type_Gether_u0/o_send_data[1]} {UDP_Type_Gether_u0/o_send_data[2]} {UDP_Type_Gether_u0/o_send_data[3]} {UDP_Type_Gether_u0/o_send_data[4]} {UDP_Type_Gether_u0/o_send_data[5]} {UDP_Type_Gether_u0/o_send_data[6]} {UDP_Type_Gether_u0/o_send_data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list UDP_Type_Gether_u0/o_send_valid]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list mmcm_u0/inst/clk_out2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 12 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {scope_top_u0/scope_data_gen_u0/ro_show_ad_data[0]} {scope_top_u0/scope_data_gen_u0/ro_show_ad_data[1]} {scope_top_u0/scope_data_gen_u0/ro_show_ad_data[2]} {scope_top_u0/scope_data_gen_u0/ro_show_ad_data[3]} {scope_top_u0/scope_data_gen_u0/ro_show_ad_data[4]} {scope_top_u0/scope_data_gen_u0/ro_show_ad_data[5]} {scope_top_u0/scope_data_gen_u0/ro_show_ad_data[6]} {scope_top_u0/scope_data_gen_u0/ro_show_ad_data[7]} {scope_top_u0/scope_data_gen_u0/ro_show_ad_data[8]} {scope_top_u0/scope_data_gen_u0/ro_show_ad_data[9]} {scope_top_u0/scope_data_gen_u0/ro_show_ad_data[10]} {scope_top_u0/scope_data_gen_u0/ro_show_ad_data[11]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list scope_top_u0/scope_data_gen_u0/ro_show_ad_data_vld]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets w_clk_50Mhz]
