# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/fifo_delay_right/fifo_delay_right.xci
# IP: The module: 'fifo_delay_right' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/fifo_delay_right/fifo_delay_right.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_delay_right'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/fifo_delay_right/fifo_delay_right_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_delay_right'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/fifo_delay_right/fifo_delay_right.xci
# IP: The module: 'fifo_delay_right' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/fifo_delay_right/fifo_delay_right.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_delay_right'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/fifo_delay_right/fifo_delay_right_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_delay_right'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
