set_property IOSTANDARD LVCMOS15 [get_ports {o_sfp_dis[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {o_sfp_dis[0]}]
set_property PACKAGE_PIN R4 [get_ports i_clk_50M]
set_property PACKAGE_PIN F10 [get_ports i_gtref_clk_p]
set_property IOSTANDARD LVCMOS15 [get_ports i_clk_50M]
set_property PACKAGE_PIN Y6 [get_ports {o_sfp_dis[1]}]
set_property PACKAGE_PIN V5 [get_ports {o_sfp_dis[0]}]

set_property PACKAGE_PIN B4 [get_ports {gt_txp[0]}]
set_property PACKAGE_PIN D5 [get_ports {gt_txp[1]}]


#以太网
set_property IOSTANDARD LVCMOS33 [get_ports {i_rxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_rxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_rxd[0]}]
set_property PACKAGE_PIN Y19 [get_ports {i_rxd[3]}]
set_property PACKAGE_PIN AB22 [get_ports {i_rxd[2]}]
set_property PACKAGE_PIN AB21 [get_ports {i_rxd[1]}]
set_property PACKAGE_PIN Y22 [get_ports {i_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_txd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_txd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_txd[0]}]
set_property PACKAGE_PIN P20 [get_ports {o_txd[3]}]
set_property PACKAGE_PIN T20 [get_ports {o_txd[2]}]
set_property PACKAGE_PIN W21 [get_ports {o_txd[1]}]
set_property PACKAGE_PIN W22 [get_ports {o_txd[0]}]

set_property PACKAGE_PIN Y21 [get_ports i_rx_ctl]
set_property PACKAGE_PIN W20 [get_ports o_tx_ctl]
set_property PACKAGE_PIN Y18 [get_ports i_rxc]
set_property PACKAGE_PIN W19 [get_ports o_txc]
set_property IOSTANDARD LVCMOS33 [get_ports i_rx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports i_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports o_tx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports o_txc]

#CAMERA
create_clock -period 40.000 -name cmos_pclk [get_ports cam_pclk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cam_pclk_IBUF]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports cam_pclk]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports cam_rst_n]
set_property -dict {PACKAGE_PIN AB18 IOSTANDARD LVCMOS33} [get_ports cam_pwdn]
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33 IOB TRUE} [get_ports {cam_data[0]}]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33 IOB TRUE} [get_ports {cam_data[1]}]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33 IOB TRUE} [get_ports {cam_data[2]}]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33 IOB TRUE} [get_ports {cam_data[3]}]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33 IOB TRUE} [get_ports {cam_data[4]}]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33 IOB TRUE} [get_ports {cam_data[5]}]
set_property -dict {PACKAGE_PIN W17 IOSTANDARD LVCMOS33 IOB TRUE} [get_ports {cam_data[6]}]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33 IOB TRUE} [get_ports {cam_data[7]}]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports cam_vsync]
set_property -dict {PACKAGE_PIN N14 IOSTANDARD LVCMOS33} [get_ports cam_href]
set_property -dict {PACKAGE_PIN N13 IOSTANDARD LVCMOS33} [get_ports cam_scl]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports cam_sda]

set_property PACKAGE_PIN U7 [get_ports i_clk_50M_rst_n]
set_property IOSTANDARD LVCMOS15 [get_ports i_clk_50M_rst_n]
 