# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/PLLA/PLLA.xci
# IP: The module: 'PLLA' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/PLLA/PLLA_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLLA'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/PLLA/PLLA.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLLA'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/PLLA/PLLA_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLLA'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/PLLA/PLLA.xci
# IP: The module: 'PLLA' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/PLLA/PLLA_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLLA'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/PLLA/PLLA.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLLA'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/PLLA/PLLA_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLLA'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
