#
# set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets clk]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports clk]
set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS33} [get_ports reset_n]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports iic_0_scl]
set_property -dict {PACKAGE_PIN F17 IOSTANDARD LVCMOS33} [get_ports iic_0_sda]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports I2S_ADCDAT]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports I2S_ADCLRC]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports I2S_DACDAT]
set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVCMOS33} [get_ports I2S_MCLK]
#


create_clock -period 20.000 [get_ports clk]
create_clock -period 80.000 [get_ports I2S_BCLK]
# aud_bclk
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets I2S_BCLK_IBUF]
set_property -dict {PACKAGE_PIN M18 IOSTANDARD LVCMOS33} [get_ports I2S_BCLK]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets I2S_ADCLRC_IBUF]
set_property PACKAGE_PIN J16 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports led]


set_property IOSTANDARD LVCMOS33 [get_ports bclk_outdac]
set_property PACKAGE_PIN T15 [get_ports bclk_outdac]


# set_property IOSTANDARD LVCMOS33 [get_ports I2S_BCLK]
# set_property IOSTANDARD LVCMOS33 [get_ports clk]
# set_property IOSTANDARD LVCMOS33 [get_ports I2S_ADCDAT]
# set_property IOSTANDARD LVCMOS33 [get_ports I2S_ADCLRC]
# set_property IOSTANDARD LVCMOS33 [get_ports I2S_DACDAT]
# set_property IOSTANDARD LVCMOS33 [get_ports I2S_DACLRC]
# set_property IOSTANDARD LVCMOS33 [get_ports I2S_MCLK]
# # set_property IOSTANDARD LVCMOS33 [get_ports I2S_out_DACDAT]
# # set_property IOSTANDARD LVCMOS33 [get_ports I2S_out_DACLRC]
# set_property IOSTANDARD LVCMOS33 [get_ports iic_0_scl]
# set_property IOSTANDARD LVCMOS33 [get_ports iic_0_sda]
# set_property IOSTANDARD LVCMOS33 [get_ports led]
# set_property IOSTANDARD LVCMOS33 [get_ports reset_n]

# set_property PACKAGE_PIN M19 [get_ports I2S_BCLK]
# set_property PACKAGE_PIN J14 [get_ports I2S_ADCDAT]
# set_property PACKAGE_PIN L16 [get_ports I2S_ADCLRC]
# set_property PACKAGE_PIN U19 [get_ports I2S_DACDAT]
# set_property PACKAGE_PIN N20 [get_ports I2S_DACLRC]
# set_property PACKAGE_PIN M20 [get_ports I2S_MCLK]
# # set_property PACKAGE_PIN W6 [get_ports I2S_out_DACDAT]
# # set_property PACKAGE_PIN Y7 [get_ports I2S_out_DACLRC]
# set_property PACKAGE_PIN M15 [get_ports iic_0_scl]
# set_property PACKAGE_PIN K14 [get_ports iic_0_sda]
# set_property PACKAGE_PIN J16 [get_ports led]
# set_property PACKAGE_PIN U18 [get_ports clk]
# set_property PACKAGE_PIN N16 [get_ports reset_n]
# set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets I2S_BCLK_IBUF]
# # set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets I2S_out_DACLRC_OBUF]

# set_property IOSTANDARD LVCMOS33 [get_ports vin]
# set_property PACKAGE_PIN P18 [get_ports vin]
# set_property PACKAGE_PIN T20 [get_ports gnd]
# set_property IOSTANDARD LVCMOS33 [get_ports gnd]
# set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets I2S_DACLRC_IBUF]





set_property IOSTANDARD LVCMOS33 [get_ports {i_rxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_rxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_txd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_txd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_txd[0]}]
set_property PACKAGE_PIN B19 [get_ports {i_rxd[0]}]
set_property PACKAGE_PIN A20 [get_ports {i_rxd[1]}]
set_property PACKAGE_PIN H17 [get_ports {i_rxd[2]}]
set_property PACKAGE_PIN H16 [get_ports {i_rxd[3]}]
set_property PACKAGE_PIN D18 [get_ports {o_txd[0]}]
set_property PACKAGE_PIN C20 [get_ports {o_txd[1]}]
set_property PACKAGE_PIN D19 [get_ports {o_txd[2]}]
set_property PACKAGE_PIN D20 [get_ports {o_txd[3]}]
set_property PACKAGE_PIN E17 [get_ports i_rx_ctl]
set_property PACKAGE_PIN K17 [get_ports i_rxc]
set_property PACKAGE_PIN K18 [get_ports o_tx_ctl]
set_property PACKAGE_PIN B20 [get_ports o_txc]
set_property IOSTANDARD LVCMOS33 [get_ports o_txc]
set_property IOSTANDARD LVCMOS33 [get_ports o_tx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports i_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports i_rx_ctl]

set_property IOSTANDARD LVCMOS33 [get_ports o_eth_rst_n]
set_property PACKAGE_PIN G15 [get_ports o_eth_rst_n]


set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_1_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_1_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_1_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_1_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_1_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_1_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_1_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_1_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_1_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_1_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_1_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_1_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_1_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_1_data[0]}]
set_property PACKAGE_PIN U5 [get_ports {o_dac_1_data[0]}]
set_property PACKAGE_PIN V7 [get_ports {o_dac_1_data[2]}]
set_property PACKAGE_PIN W8 [get_ports {o_dac_1_data[4]}]
set_property PACKAGE_PIN U9 [get_ports {o_dac_1_data[6]}]
set_property PACKAGE_PIN U10 [get_ports {o_dac_1_data[8]}]
set_property PACKAGE_PIN W6 [get_ports {o_dac_1_data[10]}]
set_property PACKAGE_PIN Y7 [get_ports {o_dac_1_data[12]}]
set_property PACKAGE_PIN T5 [get_ports {o_dac_1_data[1]}]
set_property PACKAGE_PIN U7 [get_ports {o_dac_1_data[3]}]
set_property PACKAGE_PIN V8 [get_ports {o_dac_1_data[5]}]
set_property PACKAGE_PIN U8 [get_ports {o_dac_1_data[7]}]
set_property PACKAGE_PIN T9 [get_ports {o_dac_1_data[9]}]
set_property PACKAGE_PIN V6 [get_ports {o_dac_1_data[11]}]
set_property PACKAGE_PIN Y6 [get_ports {o_dac_1_data[13]}]
set_property PACKAGE_PIN Y9 [get_ports o_dac_1_clk]
set_property IOSTANDARD LVCMOS33 [get_ports o_dac_1_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_2_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_2_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_2_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_2_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_2_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_2_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_2_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_2_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_2_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_2_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_2_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_2_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_2_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dac_2_data[0]}]
set_property PACKAGE_PIN P16 [get_ports {o_dac_2_data[0]}]
set_property PACKAGE_PIN Y19 [get_ports {o_dac_2_data[2]}]
set_property PACKAGE_PIN R18 [get_ports {o_dac_2_data[4]}]
set_property PACKAGE_PIN V18 [get_ports {o_dac_2_data[6]}]
set_property PACKAGE_PIN U17 [get_ports {o_dac_2_data[8]}]
set_property PACKAGE_PIN Y16 [get_ports {o_dac_2_data[10]}]
set_property PACKAGE_PIN V16 [get_ports {o_dac_2_data[12]}]
set_property PACKAGE_PIN P15 [get_ports {o_dac_2_data[1]}]
set_property PACKAGE_PIN Y18 [get_ports {o_dac_2_data[3]}]
set_property PACKAGE_PIN T17 [get_ports {o_dac_2_data[5]}]
set_property PACKAGE_PIN V17 [get_ports {o_dac_2_data[7]}]
set_property PACKAGE_PIN T16 [get_ports {o_dac_2_data[9]}]
set_property PACKAGE_PIN Y17 [get_ports {o_dac_2_data[11]}]
set_property PACKAGE_PIN T14 [get_ports {o_dac_2_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports o_dac_2_clk]
set_property PACKAGE_PIN W16 [get_ports o_dac_2_clk]


