# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/a000_real/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/RAM_8x1500_TrueDual/RAM_8x1500_TrueDual.xci
# IP: The module: 'RAM_8x1500_TrueDual' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/a000_real/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/RAM_8x1500_TrueDual/RAM_8x1500_TrueDual_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_8x1500_TrueDual'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/a000_real/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/RAM_8x1500_TrueDual/RAM_8x1500_TrueDual.xci
# IP: The module: 'RAM_8x1500_TrueDual' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/a000_real/logic_eth/project_1/project_1.srcs/sources_1/ip/udp/RAM_8x1500_TrueDual/RAM_8x1500_TrueDual_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_8x1500_TrueDual'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
