# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 5
create_project -in_memory -part xc7a200tfbg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/camara/a200t_auro/project_1/project_1.cache/wt [current_project]
set_property parent.project_path E:/camara/a200t_auro/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/camara/a200t_auro/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/camara/a200t_auro/src/aurora_8b10b_0_cdc_sync_exdes.v
  E:/camara/a200t_auro/src/aurora_8b10b_0_clock_module.v
  E:/camara/a200t_auro/src/aurora_8b10b_0_gt_common_wrapper.v
  E:/camara/a200t_auro/src/aurora_8b10b_0_support_reset_logic.v
  E:/camara/a200t_auro/src/aurora_channel.v
  E:/camara/a200t_auro/src/aurora_module.v
  E:/camara/a200t_auro/src/ov5640/i2c_dri.v
  E:/camara/a200t_auro/src/ov5640/i2c_ov5640_rgb565_cfg.v
  E:/camara/a200t_auro/src/ov5640/img_data_pkt.v
  E:/camara/a200t_auro/src/rst_gen_module.v
  E:/camara/a200t_auro/src/xc7a200t.v
}
read_ip -quiet E:/camara/a200t_auro/project_1/project_1.srcs/sources_1/ip/aurora_8b10b_0/aurora_8b10b_0.xci
set_property used_in_implementation false [get_files -all e:/camara/a200t_auro/project_1/project_1.srcs/sources_1/ip/aurora_8b10b_0/aurora_8b10b_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/camara/a200t_auro/project_1/project_1.srcs/sources_1/ip/aurora_8b10b_0/aurora_8b10b_0.xdc]
set_property used_in_implementation false [get_files -all e:/camara/a200t_auro/project_1/project_1.srcs/sources_1/ip/aurora_8b10b_0/aurora_8b10b_0_ooc.xdc]

read_ip -quiet E:/camara/a200t_auro/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/camara/a200t_auro/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/camara/a200t_auro/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/camara/a200t_auro/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet E:/camara/a200t_auro/project_1/project_1.srcs/sources_1/ip/async_fifo_2048x8b/async_fifo_2048x8b.xci
set_property used_in_implementation false [get_files -all e:/camara/a200t_auro/project_1/project_1.srcs/sources_1/ip/async_fifo_2048x8b/async_fifo_2048x8b.xdc]
set_property used_in_implementation false [get_files -all e:/camara/a200t_auro/project_1/project_1.srcs/sources_1/ip/async_fifo_2048x8b/async_fifo_2048x8b_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/camara/a200t_auro/project_1/project_1.srcs/sources_1/ip/async_fifo_2048x8b/async_fifo_2048x8b_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/camara/a200t_auro/project_1/project_1.srcs/constrs_1/new/sm.xdc
set_property used_in_implementation false [get_files E:/camara/a200t_auro/project_1/project_1.srcs/constrs_1/new/sm.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top XC7A200_TOP -part xc7a200tfbg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef XC7A200_TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file XC7A200_TOP_utilization_synth.rpt -pb XC7A200_TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
