# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/a000_real/logic_eth/project_1/project_1.srcs/sources_1/ip/BRAM_8X1024/BRAM_8X1024.xci
# IP: The module: 'BRAM_8X1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/a000_real/logic_eth/project_1/project_1.srcs/sources_1/ip/BRAM_8X1024/BRAM_8X1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_8X1024'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/a000_real/logic_eth/project_1/project_1.srcs/sources_1/ip/BRAM_8X1024/BRAM_8X1024.xci
# IP: The module: 'BRAM_8X1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/a000_real/logic_eth/project_1/project_1.srcs/sources_1/ip/BRAM_8X1024/BRAM_8X1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_8X1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
