# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/a000_real/logic_eth/project_1/project_1.srcs/sources_1/ip/ASYNC_FIFO_1X16/ASYNC_FIFO_1X16.xci
# IP: The module: 'ASYNC_FIFO_1X16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/a000_real/logic_eth/project_1/project_1.srcs/sources_1/ip/ASYNC_FIFO_1X16/ASYNC_FIFO_1X16.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASYNC_FIFO_1X16'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/a000_real/logic_eth/project_1/project_1.srcs/sources_1/ip/ASYNC_FIFO_1X16/ASYNC_FIFO_1X16_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASYNC_FIFO_1X16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/a000_real/logic_eth/project_1/project_1.srcs/sources_1/ip/ASYNC_FIFO_1X16/ASYNC_FIFO_1X16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASYNC_FIFO_1X16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/a000_real/logic_eth/project_1/project_1.srcs/sources_1/ip/ASYNC_FIFO_1X16/ASYNC_FIFO_1X16.xci
# IP: The module: 'ASYNC_FIFO_1X16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/a000_real/logic_eth/project_1/project_1.srcs/sources_1/ip/ASYNC_FIFO_1X16/ASYNC_FIFO_1X16.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASYNC_FIFO_1X16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/a000_real/logic_eth/project_1/project_1.srcs/sources_1/ip/ASYNC_FIFO_1X16/ASYNC_FIFO_1X16_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASYNC_FIFO_1X16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/a000_real/logic_eth/project_1/project_1.srcs/sources_1/ip/ASYNC_FIFO_1X16/ASYNC_FIFO_1X16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASYNC_FIFO_1X16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
