# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.cache/wt [current_project]
set_property parent.project_path E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/ARP_Table.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/ARP_rx.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/ARP_tx.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/cdc/AXIS_BUF_2CLK_8X2048.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/CRC32_D8.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/CRC_Data_Pro.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/Data_2to1.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/Ethernet_ARP.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/Ethernet_ICMP.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/Ethernet_IP.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/Ethernet_MAC.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/Ethernet_UDP.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/GMII2RGMII_Drive.v
  E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/new/I2C_Init_Dev.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/ICMP_rx.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/ICMP_tx.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/IP_rx.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/IP_tx.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/MAC_rx.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/MAC_tx.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/RGMII_RAM.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/RGMII_Tri.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/UDP_Stack_Module.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/UDP_rx.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/UDP_tx.v
  E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/new/WM8960_Init.v
  E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/new/allcross_iir.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/async_fifo_ctrl.v
  E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/new/comb.v
  E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/new/delay_module.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/dpram.v
  E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/new/effects_select.v
  E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/new/equalier_control.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/fir.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/fir_complex.v
  E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/new/i2c_bit_shift.v
  E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/new/i2c_control.v
  E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/new/i2s_rx.v
  E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/new/i2s_tx.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/interpolation_top.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/UDP/mac_arp_ip_mux.v
  E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/new/reverb.v
  E:/a00aa_music/vivado_Music/vivado_Music/src/rst/rst_gen_module.v
  E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/new/sys_divi.v
  E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/new/wm8960_init_table.v
  E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/new/audio_lookback.v
}
read_ip -quiet E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/FIFO_16X16_2CLK/FIFO_16X16_2CLK.xci
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/FIFO_16X16_2CLK/FIFO_16X16_2CLK.xdc]
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/FIFO_16X16_2CLK/FIFO_16X16_2CLK_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/FIFO_16X16_2CLK/FIFO_16X16_2CLK_ooc.xdc]

read_ip -quiet E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/FIFO_8X2048_2CLK/FIFO_8X2048_2CLK.xci
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/FIFO_8X2048_2CLK/FIFO_8X2048_2CLK.xdc]
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/FIFO_8X2048_2CLK/FIFO_8X2048_2CLK_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/FIFO_8X2048_2CLK/FIFO_8X2048_2CLK_ooc.xdc]

read_ip -quiet E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/FIFO_ASYNC_11_64/FIFO_ASYNC_11_64.xci
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/FIFO_ASYNC_11_64/FIFO_ASYNC_11_64.xdc]
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/FIFO_ASYNC_11_64/FIFO_ASYNC_11_64_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/FIFO_ASYNC_11_64/FIFO_ASYNC_11_64_ooc.xdc]

read_ip -quiet E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/RAM_8_1600/RAM_8_1600.xci
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/RAM_8_1600/RAM_8_1600_ooc.xdc]

read_ip -quiet E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/FIFO_16X64/FIFO_16X64.xci
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/FIFO_16X64/FIFO_16X64.xdc]
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/FIFO_16X64/FIFO_16X64_ooc.xdc]

read_ip -quiet E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/FIFO_11X64/FIFO_11X64.xci
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/FIFO_11X64/FIFO_11X64.xdc]
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/FIFO_11X64/FIFO_11X64_ooc.xdc]

read_ip -quiet E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/RAM_8x1500_TrueDual/RAM_8x1500_TrueDual.xci
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/RAM_8x1500_TrueDual/RAM_8x1500_TrueDual_ooc.xdc]

read_ip -quiet E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/FIFO_MAC_8X64/FIFO_MAC_8X64.xci
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/FIFO_MAC_8X64/FIFO_MAC_8X64.xdc]
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/FIFO_MAC_8X64/FIFO_MAC_8X64_ooc.xdc]

read_ip -quiet E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/FIFO_32X16/FIFO_32X16.xci
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/FIFO_32X16/FIFO_32X16.xdc]
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/FIFO_32X16/FIFO_32X16_ooc.xdc]

read_ip -quiet E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/FIFO_8X256/FIFO_8X256.xci
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/FIFO_8X256/FIFO_8X256.xdc]
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/FIFO_8X256/FIFO_8X256_ooc.xdc]

read_ip -quiet E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/RAM_MAC/RAM_MAC.xci
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/RAM_MAC/RAM_MAC_ooc.xdc]

read_ip -quiet E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/RAM_IP/RAM_IP.xci
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/udp/RAM_IP/RAM_IP_ooc.xdc]

read_ip -quiet E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/PLLA/PLLA.xci
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/PLLA/PLLA_board.xdc]
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/PLLA/PLLA.xdc]
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/PLLA/PLLA_ooc.xdc]

read_ip -quiet E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/fifo_delay_right/fifo_delay_right.xci
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/fifo_delay_right/fifo_delay_right.xdc]
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/fifo_delay_right/fifo_delay_right_ooc.xdc]

read_ip -quiet E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/fifo_delay_left_1/fifo_delay_left.xci
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/fifo_delay_left_1/fifo_delay_left.xdc]
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/fifo_delay_left_1/fifo_delay_left_ooc.xdc]

read_ip -quiet E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/constrs_1/new/vivado_Music.xdc
set_property used_in_implementation false [get_files E:/a00aa_music/vivado_Music/vivado_Music/vivado_Music.srcs/constrs_1/new/vivado_Music.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top audio_lookback -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef audio_lookback.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file audio_lookback_utilization_synth.rpt -pb audio_lookback_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
