# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/vivado_Music.xdc

# IP: ip/FIFO_16X16_2CLK/FIFO_16X16_2CLK.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_16X16_2CLK || ORIG_REF_NAME==FIFO_16X16_2CLK} -quiet] -quiet

# IP: ip/FIFO_8X2048_2CLK/FIFO_8X2048_2CLK.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_8X2048_2CLK || ORIG_REF_NAME==FIFO_8X2048_2CLK} -quiet] -quiet

# IP: ip/udp/FIFO_ASYNC_11_64/FIFO_ASYNC_11_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_ASYNC_11_64 || ORIG_REF_NAME==FIFO_ASYNC_11_64} -quiet] -quiet

# IP: ip/udp/RAM_8_1600/RAM_8_1600.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_8_1600 || ORIG_REF_NAME==RAM_8_1600} -quiet] -quiet

# IP: ip/udp/FIFO_16X64/FIFO_16X64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_16X64 || ORIG_REF_NAME==FIFO_16X64} -quiet] -quiet

# IP: ip/udp/FIFO_11X64/FIFO_11X64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_11X64 || ORIG_REF_NAME==FIFO_11X64} -quiet] -quiet

# IP: ip/udp/RAM_8x1500_TrueDual/RAM_8x1500_TrueDual.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_8x1500_TrueDual || ORIG_REF_NAME==RAM_8x1500_TrueDual} -quiet] -quiet

# IP: ip/udp/FIFO_MAC_8X64/FIFO_MAC_8X64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_MAC_8X64 || ORIG_REF_NAME==FIFO_MAC_8X64} -quiet] -quiet

# IP: ip/udp/FIFO_32X16/FIFO_32X16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_32X16 || ORIG_REF_NAME==FIFO_32X16} -quiet] -quiet

# IP: ip/udp/FIFO_8X256/FIFO_8X256.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_8X256 || ORIG_REF_NAME==FIFO_8X256} -quiet] -quiet

# IP: ip/udp/RAM_MAC/RAM_MAC.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_MAC || ORIG_REF_NAME==RAM_MAC} -quiet] -quiet

# IP: ip/udp/RAM_IP/RAM_IP.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_IP || ORIG_REF_NAME==RAM_IP} -quiet] -quiet
