# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/a000_real/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_8X8192/FIFO_8X8192.xci
# IP: The module: 'FIFO_8X8192' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/a000_real/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_8X8192/FIFO_8X8192.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_8X8192'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/a000_real/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_8X8192/FIFO_8X8192_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_8X8192'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/a000_real/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_8X8192/FIFO_8X8192.xci
# IP: The module: 'FIFO_8X8192' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/a000_real/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_8X8192/FIFO_8X8192.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_8X8192'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/a000_real/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_8X8192/FIFO_8X8192_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_8X8192'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
