# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_10X128/FIFO_10X128.xci
# IP: The module: 'FIFO_10X128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_10X128/FIFO_10X128.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_10X128'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_10X128/FIFO_10X128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_10X128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_10X128/FIFO_10X128.xci
# IP: The module: 'FIFO_10X128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_10X128/FIFO_10X128.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_10X128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/a000_real_side/logic_eth/project_1/project_1.srcs/sources_1/ip/FIFO_10X128/FIFO_10X128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_10X128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
